/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

// post

export const RESET_POST = 'RESET_POST';
export const ADD_FILES = 'ADD_FILES';
export const REMOVE_FILE = 'REMOVE_FILE';
export const SET_TAGS = 'SET_TAGS';
export const SET_LINK = 'SET_LINK';
export const BEGIN_POST = 'BEGIN_POST';
export const POST_AWS_REQUEST = 'POST_AWS_REQUEST';
export const POST_AWS_ON_PROGRESS = 'POST_AWS_ON_PROGRESS';
export const POST_AWS_SUCCESS = 'POST_AWS_SUCCESS';
export const POST_AWS_FAILURE = 'POST_AWS_FAILURE';
export const POST_GRAPHQL_REQUEST = 'POST_GRAPHQL_REQUEST';
export const POST_GRAPHQL_SUCCESS = 'POST_GRAPHQL_SUCCESS';
export const POST_GRAPHQL_FAILURE = 'POST_GRAPHQL_FAILURE';
export const END_POST = 'END_POST';

// feed
export const FETCH_FEED_REQUEST = 'FETCH_FEED_REQUEST';
export const FETCH_FEED_SUCCESS = 'FETCH_FEED_SUCCESS';
export const FETCH_FEED_FAILURE = 'FETCH_FEED_FAILURE';
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';
export const REMOVE_COMMENT_REQUEST = 'REMOVE_COMMENT_REQUEST';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_FAILURE = 'REMOVE_COMMENT_FAILURE';
export const ADD_CHECK_REQUEST = 'ADD_CHECK_REQUEST';
export const ADD_CHECK_SUCCESS = 'ADD_CHECK_SUCCESS';
export const ADD_CHECK_FAILURE = 'ADD_CHECK_FAILURE';
export const REMOVE_CHECK_REQUEST = 'REMOVE_CHECK_REQUEST';
export const REMOVE_CHECK_SUCCESS = 'REMOVE_CHECK_SUCCESS';
export const REMOVE_CHECK_FAILURE = 'REMOVE_CHECK_FAILURE';
export const UPDATE_CHECK_REQUEST = 'UPDATE_CHECK_REQUEST';
export const UPDATE_CHECK_SUCCESS = 'UPDATE_CHECK_SUCCESS';
export const UPDATE_CHECK_FAILURE = 'UPDATE_CHECK_FAILURE';

// user
export const USER_LOGOUT = 'USER_LOGOUT';
